---
# tasks file for vm_build_bracknell
- name: Remove "{{ vm_name }}"
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_server }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: absent
  delegate_to: localhost
  register: facts
  tags:
    - remove_vm

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: deploy
