---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.12'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
    # system: bindep.txt
