---
# tasks file for os_config_webserver
#
#
- name: configure DNS
  copy:
    content: "nameserver 10.250.210.1"
    dest: /etc/resolv.conf
- name: install required packages
  yum:
    name:
      - httpd
      - firewalld
    state: present
- name: configure firewalld
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled
    notify: restart firewalld
- name: copy html template
  template:
    src: index.html.j2
    dest: /var/www/html/index.hmtl
    notify: restart httpd

