---
# tasks file for os_config_webserver
#
#
- name: configure DNS
  copy:
    content: "nameserver 10.250.210.1"
    dest: /etc/resolv.conf

- name: install required packages
  yum:
    name:
      - httpd
      - firewalld
      - git-all
    state: present

- name: configure firewalld
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled
  notify: restart firewalld

- name: clone git repo
  ansible.builtin.git:
    repo: https://github.com/darrylkelly88/bracknell.git
    dest: /root/dell-project

- name: copy website assets to /var/www/html
  copy:
    src: /root/dell-project/dell_demo_website/assets/
    dest: /var/www/html/assets
    remote_src: yes
    group: "apache"
    owner: "apache"
    directory_mode: yes

- name: modify security context to allow loading of website assets
  sefcontext:
    target: '/var/www/html/assets(/.*)?'
    setype: httpd_sys_content_t
    state: present

- name: apply new security context
  command: restorecon -R -ivf /var/www/html/assets/

- name: copy html template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    group: "apache"
    owner: "apache"
  notify: restart httpd

- debug:
    var: hostvars['localhost']['powerstore_facts']['ProtectionPolicies']

- name: debug - copy j2 template
  template:
    src: test_template.html.j2
    dest: /var/www/html/test.html
  notify: restart httpd