---
# tasks file for os_config_webserver
#
#
- name: configure DNS
  copy:
    content: "nameserver 10.250.210.1"
    dest: /etc/resolv.conf

- name: install required packages
  yum:
    name:
      - httpd
      - firewalld
      - git-all
    state: present

- name: configure firewalld
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled
  notify: restart firewalld

- name: clone git repo
  ansible.builtin.git:
    repo: https://github.com/darrylkelly88/bracknell.git
    dest: /root/dell-project

- name: copy website assets
  copy:
    src: /root/dell-project/dell_demo_website/assets
    dest: /var/www/html/assets

- name: copy html template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html.j2
  notify: restart httpd

