---
# tasks file for os_config_webserver
#
#
- name: install required packages
  yum:
    name:
      - httpd
      - firewalld
    state: present
- name: configure firewalld
  ansible.posix.firewalld:
    service: http
    permenent: yes
    state: enabled
    notify: restart firewalld
- name: copy html template
  template:
    src: index.html.j2
    dest: /var/www/html/index.hmtl
    notify: restart httpd

