---
# tasks file for os_config_webserver
#
#
- name: configure DNS
  copy:
    content: "nameserver 10.250.210.1"
    dest: /etc/resolv.conf

- name: install required packages
  yum:
    name:
      - httpd
      - firewalld
      - git-all
    state: present

- name: configure firewalld
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled
  notify: restart firewalld

- name: clone git repo
  ansible.builtin.git:
    repo: https://github.com/darrylkelly88/alexaweb.git
    dest: /root/alexa-demo

- name: copy website assets to /var/www/html
  copy:
    src: /root/alexa-demo/alexa_demo_web/assets/
    dest: /var/www/html/assets
    remote_src: yes
    group: "apache"
    owner: "apache"
    directory_mode: yes
    setype: httpd_sys_content_t
 # notify: set security context

- name: set security context
  community.general.sefcontext:
    target: '/var/www/html(/.*)?'
    setype: httpd_sys_content_t
    state: present
  notify: ensure security permenance

- name: copy html template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    group: "apache"
    owner: "apache"
    setype: httpd_sys_content_t
  notify: restart httpd

#- debug:
#    var: hostvars['localhost']['powerstore_facts']['ProtectionPolicies']
#
#- name: debug - copy j2 template
#  template:
#    src: test_template.html.j2
#    dest: /var/www/html/test.html
#  notify: restart httpd
