---
# tasks file for vm_build_bracknell
- name: Remove "{{ vm_name }}"
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: absent
  delegate_to: localhost
  register: facts
  tags:
    - remove_vm
